### ISSUE TITLE
How can I cite your package?

### ISSUE THREAD

**Issue by 4daJKong** [enry12/self_organizing_map#4]
Sorry to bother you. I am a CS student and I am working on a project focused on two-dimensional SOM and growing hierarchical SOM. Your source code is helpful when I construct my code. May I cite your repository in my project, if so, how?

**Comment by fteotini** [comment]
Hi @4daJKong, we're very glad you found this little repo useful!

You can cite it with the following

Civitelli E., Teotini F. (2018) Growing Hierarchical SOM [Source Code]
https://github.com/enry12/growing_hierarchical_som
